permalink:           pretty

# Setup
title:               'JekyllBook'
#tagline:             'A Jekyll theme'
url:                 https://subhadarship.github.io/kmeans_pytorch/
baseurl:             '/docs'

# About/contact
author:
  name:              Subhadarshi Panda
  url:               subhadarship.github.io
github:
  repo:              https://github.com/subhadarship/kmeans_pytorch/

# Custom vars
version:             0.3

multilingual:        false
src:                 "."
default_theme:       "ayu"

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable : true

# Chapter Configuration (up to a 2 level nested list)

chapters:
  - path: example.md
  - path: cpu_vs_gpu.md

